### ISSUE TITLE
Accessing BTC  market always freeze 30 seconds or more 

### ISSUE THREAD

**Issue by btswildpig** [BitShares/web_wallet#525]
Accessing BTC:BTS market always freeze 30 seconds or more on loading

**Comment by vikramrajkumar** [comment]
@valzav There have been many complaints about this (see https://github.com/BitShares/bitshares/issues/1192 and https://bitsharestalk.org/index.php?topic=13320.0 for example). 

Can you figure out whether this is something in the frontend or backend that is causing the freezing?

**Comment by valzav** [comment]
I'm not able to replicate this issue on mac. I'll give it one more try on Windows next monday.

**Comment by vikramrajkumar** [comment]
@valzav I believe most if not all of the reports I've seen have been on Windows. That may not be related, however--it may just be the case that the market page makes a lot of slow RPC calls. Could you take a look whether the RPC calls could be a problematic? I imagine listing the entire book requires iterating many databases in the backed.

There have also been some freezing issues due to scanning which I have recently fixed in develop branch, and which may have contributed to this.

**Comment by vikramrajkumar** [comment]
Possibly related: #1202

**Comment by vikramrajkumar** [comment]
Possibly related: https://github.com/BitShares/bitshares/issues/1202

**Comment by vikramrajkumar** [comment]
@btswildpig Can you confirm whether this is still a problem in BTS 0.6.0 ?

**Comment by vikramrajkumar** [comment]
Not enough info; assuming resolved.
