### ISSUE TITLE
Cannot Download http://get.syncad.com/invictus/Bitshare_toolkit_prebuilt_libs-vs2013-x64.7z

### ISSUE THREAD

**Issue by Dannynz** [BitShares/web_wallet#699]
Hi There,

At the moment, I cannot go to this link http://get.syncad.com/invictus/Bitshare_toolkit_prebuilt_libs-vs2013-x64.7z. Anyone got the same problem, please give me some advice. Thank you so much.

**Comment by abitmore** [comment]
New links for downloading:
* Bitshare_toolkit_prebuilt_libs-vs2013-x64.7z: https://drive.google.com/open?id=1bFdKuVPmgfHycHSKUQ_R9jC0bo5Bk1tI
* Bitshare_toolkit_prebuilt_libs-vs2013.7z: https://drive.google.com/open?id=1GyIkKZuIavFUithXnD5SW3q8choL6gka

Since BitShares has been upgraded, nobody is now producing blocks in the 0.9 chain, this repository is no longer maintained. Please check https://github.com/bitshares/bitshares-core for latest info.
